version: '2'

services:
  magento:
    container_name: ${MAGENTO_NAME}
    restart: always
    image: daprejean/magento:latest
    volumes:
    - ./magento:/var/www/html
    ports:
    - "${MAGENTO_EXTERNAL_HTTP_PORT}:80"
    - "${MAGENTO_EXTERNAL_HTTPS_PORT}:443"
    environment:
    - HTTP_PROXY
    - HTTPS_PROXY
    - LOCAL_USER_ID
    - LOCAL_GROUP_ID
    - DB_HOST
    - DB_USER
    - DB_PASSWORD
    - DB_NAME
    - REDIS_HOST
    - REDIS_SESSION_PORT
    - REDIS_FPC_PORT
    - REDIS_FPC_PREFIX
    - REDIS_CACHE_PORT
