version: '2'

services:
  magento:
    container_name: ${MAGENTO_NAME}
    restart: always
    image: daprejean/magento:latest
    volumes:
    - ./magento:/var/www/html
    ports:
    - "${MAGENTO_EXTERNAL_HTTP_PORT}:80"
    - "${MAGENTO_EXTERNAL_HTTPS_PORT}:443"
    links:
    - redis:redis_host
    - mysql:mysql_host
    environment:
    - HTTP_PROXY=${HTTP_PROXY}
    - HTTPS_PROXY=${HTTPS_PROXY}
    - LOCAL_USER_ID=${LOCAL_USER_ID}
    - LOCAL_GROUP_ID=${LOCAL_GROUP_ID}
    - DB_HOST=${DB_HOST}
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}
    - DB_NAME=${DB_NAME}
    - REDIS_HOST=${REDIS_HOST}
    - REDIS_SESSION_PORT=${REDIS_SESSION_PORT}
    - REDIS_FPC_PORT=${REDIS_FPC_PORT}
    - REDIS_FPC_PREFIX=${REDIS_FPC_PREFIX}
    - REDIS_CACHE_PORT=${REDIS_CACHE_PREFIX}
    - REDIS_CACHE_PREFIX=${REDIS_CACHE_PREFIX}
    - REMOTE_DB_HOST=${REMOTE_DB_HOST}
    - REMOTE_DB_USER=${REMOTE_DB_USER}
    - REMOTE_DB_PASSWORD=${REMOTE_DB_PASSWORD}
    - REMOTE_DB_NAME=${REMOTE_DB_NAME}
    - LDAP_PROXY=${LDAP_PROXY}
    - LDAP_USER=${LDAP_USER}
    - LDAP_PASSWORD=${LDAP_PASSWORD}
    - LDAP_AUTH_CODE=${LDAP_AUTH_CODE}
    - MYSQL_HOST=${MYSQL_HOST}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}

  redis:
    container_name: ${MAGENTO_NAME}_redis
    restart: always
    image: redis:latest
    expose:
    - "6379"
    ports:
    - "6379:6379"

  mysql:
    container_name: ${MAGENTO_NAME}_mysql
    restart: always
    image: mysql:latest
    volumes:
    - /data/${MAGENTO_NAME}_mysql:/var/lib/mysql
    expose:
    - "3306"
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
